# -*- coding: utf-8 -*-
"""3960_CoWrangler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEqFjYI2B_ecph9Vgk9Q448nRgp9UlBV
"""

import pandas as pd

import ipywidgets as widgets
from IPython.display import display
w = widgets.IntSlider()
display(w)